[project]
name = "evtr2py"
version = "0.1.0"
description = "Use r2py to run non-stationary EVT model in python"
license = "CC-BY-NC-ND-4.0"
license-files = ["license.txt"]
readme = "README.md"
authors = [
    { name = "Carolien Mossel", email = "cmossel@gradcenter.cuny.edu" },
    { name = "Naresh Devineni", email = "ndevineni@ccny.cuny.edu" }
]
dependencies = []

[project.optional-dependencies]
examples = [
    "jupyter",
    "matplotlib",
]
docs = [
    "mkdocs-material","mkdocs-bootstrap386 @ git+https://gitlab.com/lramage/mkdocs-bootstrap386.git",
"pyyaml-env-tag",
]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

